services:
  # 1. Backend Web Service
  - type: web
    name: healthconnect-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://rithuanumula5_db_user:e4xF1ra2DdjZV5QM@healthconnect.nl0o00n.mongodb.net/healthconnect?retryWrites=true&w=majority&appName=healthconnect
      - key: JWT_SECRET
        value: healthconnect_jwt_secret_key_123456

  # 2. Frontend Static Site
  - type: web
    name: healthconnect-frontend
    env: static
    plan: free
    rootDir: frontend
    buildCommand: npm install && npm run build
    publishDir: dist
    envVars:
      - key: VITE_API_URL
        fromService:
          name: healthconnect-backend
          type: web
          property: url
